sudo: required
services:
  - docker

before_install:
  - docker build -t timmyaa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true timmyaa/react-test npm test 

after_success:
  - docker build -t timmyaa/multi-client ./client
  - docker build -t timmyaa/multi-nginx ./nginx
  - docker build -t timmyaa/multi-server ./server
  - docker build -t timmyaa/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push timmyaa/multi-client
  - docker push timmyaa/multi-nginx
  - docker push timmyaa/multi-server
  - docker push timmyaa/multi-worker

